### ISSUE TITLE
[DON'T MERGE] Update cypress version & sync our helper classes with epic/product-configuration

### ISSUE THREAD

**Issue by Larisa-Staroverova** [SAP/spartacus#10790]
See [package.json](https://github.com/SAP/spartacus/blob/epic/product-configuration/projects/storefrontapp-e2e-cypress/package.json) in epic/product-configuration

- [x] Update cypress version accordingly,
- [x] Merge epic/product-configuration
- [x] Sync projects/storefrontapp-e2e-cypress/cypress/helpers/product-configuration.ts
- [x] Sync projects/storefrontapp-e2e-cypress/cypress/helpers/product-configuration-overview.ts 
- [ ] Fix failing tests
