### ISSUE TITLE
Epic Release checklist: CPQ

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#11645]
The following is a checklist for new epics or features acceptance for Spartacus, based on [our Definition of Done document](https://sap.github.io/spartacus-docs/definition-of-done/)

## General

- [x] Epic has been tested on a production-like server using Spartacus installation script
      *There's ongoing discussion with @hackergil and @giancorderoortiz whether we should plug CPQ integration into our CI (concerns: complex environment setup; which team should own it; secret sample data).*

- [x] Epic has been tested in all supported browsers and devices (Check list on DoD page)
       *Team Tiger should test it in the end*

- [x] Epic has sufficient end to end (cypress) test coverage
       *To be reviewed by @Platonn , @WeizhengSap*

- [x] Schematics code deprecations have been provided and tested
      *The team tiger need to add feature-level guards for the breaking changes .*

- [ ] Epic code scans have been conducted (sonar, whitesource, checkmarx)
     *To be checked by @giancorderoortiz* in the end

## Audits/reviews

- [x] Architecture and code review of the epic (with @Platonn , @WeizhengSap )
- [x] Security and threat modeling audit/review from the Security team
   - [x] Epic complies with [Security best practices](https://sap.github.io/spartacus-docs/security-best-practices/)
- [x] Accessibility audit/review from the UX team (with @developpeurweb )
   - [x] Epic complies with [Accessibility best practices](https://sap.github.io/spartacus-docs/a11y-best-practices/). 
      _There are some known issues. But postponed fixing them to RC and patch releases. Some issues require breaking changes so need to be postponed to major version. @platonn_  
   - [x] Epic CSS supports directionality (if required)

## Library

If your epic will be introduced or introduces a new library or a new lazy-loadable entry point:

- [x] Library provides schematics to install the library (library part)
- [x] Library modules can be lazy loaded appropriately
- [x] Library has been tested for a customer using Spartacus installation script
    _Set in `config[.default].sh`: `ADD_CPQ=true` and `BACKEND_URL="<cpq server from .env-cmdrc>"`_

## Sample data

If the new feature requires new or updated sample data for a specific Commerce backend version:
(Note SPA CI does not support CPQ as of now, therefore we go for the Tiger CI landscape)
- [x] Sample data has been added to the sampledata repo and merged to the next version to be released https://github.tools.sap/cx-commerce/spartacussampledata/pull/171/files
- [x] New sample data has been loaded and tested on a dev server
- [x] New sample data has been loaded and tested in our CI server

## Documentation
- [x] Documentation input is provided for it to be published on the doc site.

## Notes
CPQ project board: https://github.com/SAP/spartacus/projects/107
Team Tiger's checklist: https://cxjira.sap.com/browse/TIGER-7402
Epic PR: https://github.com/SAP/spartacus/pull/11001

Manual prerequisites to test CPQ feature:
- use b2b storefront (powerools-spa sample data and b2b occ endpoints for cart, see `defaultB2bOccConfig`)
- use a commerce backend with installed CPQ integration (refer to @ChristophHi for more details)

**Comment by ChristophHi** [comment]
epic has been merged, code fulfilled static code checks. No new dependencies to 3rd party libs introduced. Hence closing the ticket
