### ISSUE TITLE
[MASTER] Flaky e2e tests list

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#12265]
List of e2e tests marked as `flaky`. Please add your name next to the test you are fixing

### Pending

- [ ] #9153 accessibility/tabbing-order.flaky-e2e-spec.ts **need to be worked once all other e2es are done. Each tabbing order test needs to be part of its own feature. This spec needs to be redistributed.***

### In progress

- [x] #12269 regression/anonymous-consents/anonymous-consents-flow.flaky-e2e-spec.ts (@hackergil)
- [x] #7523 regression/applied-promotions.flaky-e2e-spec.ts (@hackergil)
- [x] #12270 regression/site-context/language/language-checkout-page.flaky-e2e-spec.ts (@WeizhengSap )
- [x] #8215 regression/site-context/language/language-my-account-pages.flaky-e2e-spec.ts (@WeizhengSap )
- [x] #12271 regression/site-context/language/language-cart-page.flaky-e2e-spec.ts (@WeizhengSap )
- [x] #12272 regression/site-context/currency/currency-product-search.flaky-e2e-spec.ts (@bgambocjaviniar)
- [x] #12266 b2b/regression/replenishment/b2b-replenishment-checkout-flow (@bgambocjaviniar)
- [x] #7519 regression/coupon/coupon.flaky-e2e-spec.ts (@hackergil)
- [x] #7520 regression/my-coupons/my-coupons.flaky-e2e-spec.ts (@hackergil)
- [x] #12267 b2b/regression/my-company/units.flaky-e2e-spec.ts (@Pucek9) 
- [x] #11107 b2b/regression/my-company/users.flaky-e2e-spec.ts (@Pucek9) 
- [x] #11042 b2b/regression/my-company/user-groups.flaky-e2e-spec.ts (@Pucek9)

**Comment by hackergil** [comment]
Closing since most of the flaky tests have been fixed
