### ISSUE TITLE
Test Plan 4.0

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#12691]
### 1. Background

- Test plan lists the minimum necessary testing required for 4.0.0 major release.
- Planned release date: **FF end of June 2021** & **Final Release mid-July**
- Sprint reviews have demos of functionality being released. See demos
- Regression testing to be handled mostly by automated testing.
- Manual testing required for new features only (where not covered by automation)
- Testing must be done only with 4.0.0 RCx ⚠️ 
- New mandate: No major open bugs allowed. ⚠️ ⚠️ ⚠️  **Not necessarily true - if something is important enough to block the release, we say it's critical or blocker; we have 30 days after bug report to fix a bug**
- - In other words, a bug classified as major not yet resolved will block release unless exceptions are made. 

---

### 2. New features for this release
- Checkout lib. Owner: @plabadie @WeizhengSap 
- E2E fixes Owner: @hackergil 
- Angular 12 upgrade Owner: @dunqan 
- Blue there Owner @morganm58 
- Deprecation/upgrade Owner: @marlasak 
- Screen Readers. @saad-mo 

---

### 3. Commerce Suite CX Compatibility
- [x] CX 2005 https://github.com/SAP/spartacus/issues/12752
- [x] CX 2011 https://github.com/SAP/spartacus/issues/12753
- [x] CX 2105 (Remember Enable mobile_android! ) https://github.com/SAP/spartacus/issues/12754

---
### 4. Schematics
Confirm Spartacus 4.0 can be deployed in Windows, Mac, Linux using schematics script.
https://github.com/SAP/spartacus/tree/develop/scripts/install

- [ ]  Windows @dunqan 
- [x]  Linux @giancorderoortiz
- [x]  Mac @hackergil

---
### 5. Deployments
- [x] Linux server with Schematics script @giancorderoortiz 
- [x] CCV2 @LTiger14 

---
### 6. Server Links

CCV2 (SANTORINI THEME) RC1:
- [x] https://github.com/SAP/spartacus/issues/12750
   B2C https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/electronics-spa/en/USD/
   B2B https://b2bspastore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/powertools-spa/en/USD/

Linux (SPARTA THEME) RC1:
- [x] https://github.com/SAP/spartacus/issues/12751
   CSR B2C http://spartacus-devci7672.eastus.cloudapp.azure.com:4200/electronics-spa/en/USD/
   SSR B2C http://spartacus-devci7672.eastus.cloudapp.azure.com:4100/electronics-spa/en/USD/
 
   CSR B2B http://spartacus-devci7672.eastus.cloudapp.azure.com:5200/powertools-spa/en/USD/
   SSR B2B http://spartacus-devci7672.eastus.cloudapp.azure.com:5100/powertools-spa/en/USD/

---
### 7. Critical Open Bugs / QA Concerns
- [x] No Blockers bugs, no critical bugs opened prior to release.  
- [x] No major bugs either **more than 30 days old**. List of Major bugs to fix: https://github.com/SAP/spartacus/issues/12699. If a bug is serious enough that it blocks a release, set it to blocker.
- [x] Angular 12 upgrade. All e2e must pass in CI
- [x] Checkout lib. All e2e must pass in CI. 

---
### 8. SSR Testing @giancorderoortiz 

- [x] Manual testing in CCV2. Happy path. 
- [ ] E2E tests adopted to run in SSR mode. Owner @hackergil 

---
###  9. Cypress Automated Regression Testing

- [x] Run full regression suite with 4.0 release branch in CI.
-- Attach screenshot and link of dashboard with final results

- [x] Run full regression suite with 4.0 release branch (CCV2/dev server)
-- Attach screenshot and link of dashboard with final results

- [x]  Run all flaky tests either locally, CCV2 or Linux server. @giancorderoortiz 
-- In the case of actual failures, please investigate and open bugs if functional regression observed.
-- Manual execution of flaky tests here: TBD

---
###  10. New Features Automated Testing

- [x] Checkout lib - full suite regression testing. @plabadie 

---
### 11. New Features Manual Testing

- [x] Blue theme (desktop, mobile)
- [x] Windows Screen Reader. See https://github.com/SAP/spartacus/issues/12888 @dunqan (also tested by @developpeurweb) 
- [x] Mac Screen Reader. @developpeurweb 

---
### 12. New Features Security Validation

Owner: @giancorderoortiz  https://github.com/SAP/spartacus/issues/12755

- [x] Static scans
- [x] Dynamic scans
- [x] Third party libraries vulnerabilities
- [x] TM where applicable

---
### 13. New Features Accessibility Testing
Owner: @developpeurweb 

- [x] Accessibility throughout checkout flow.
- [x] Any regression due to ng12 upgrade? 
- [x] Accessibility in blue theme. 

---
### 14. New Features Mobile/Exploratory-Smoke Testing

- Several combinations of browser & OS needed for the key new features that had new UI.
- TIME-BOX this activity to no more than 1 hour per browser/os combination. ⌛ 
- Please add your name next to the browser or feature list item below.
- Create bug tickets if necessary.
- Blue theme testing doesn't block Release (team decision), but do screen capture any visual bugs.

- [x]  Desktop
- - [x] Chrome 
  - - [x] Windows @psmul 
      - [x] Blue Theme
      - [x] B2C Checkout happy path
      - [x] B2B Checkout happy path
  - - [x] Mac @mszczepaniak 
      - [x] Blue Theme
      - [x] B2C Checkout happy path
      - [x] B2B Checkout happy path
- - [x]  Firefox
  - - [x] Windows
      - [x] Blue Theme @dydome 
      - [x] B2C Checkout happy path @dydome 
      - [x] B2B Checkout happy path @dydome 
  - - [x] Mac @bgambocjaviniar 
      - [x] Blue Theme
      - [x] B2C Checkout happy path
      - [x] B2B Checkout happy path
- - [x] Safari  (Mac)
      - [x] Blue Theme @Matejk00 
      - [x] B2C Checkout happy path @Matejk00 
      - [x] B2B Checkout happy path @Matejk00 
- - [x] Edge (Windows)
      - [x] Blue Theme @dydome 
      - [x] B2C Checkout happy path @dydome 
      - [x] B2B Checkout happy path @dydome 
- [x] iOS (mobile) 
- - [x] Safari  
      - [x] Blue Theme @dydome 
      - [x] B2C Checkout happy path @saad-mo 
      - [x] B2B Checkout happy path @saad-mo 
- - [x] Chrome 
      - [x] Blue Theme @dydome 
      - [x] B2C Checkout happy path @bgambocjaviniar (iPhone 12)
      - [x] B2B Checkout happy path @bgambocjaviniar (iPhone 12)
- [x] iOS (Tablet - iPad Air, Pro, etc) 
- - [x] Safari @bgambocjaviniar (iPad Pro)
      - [x] Blue Theme
      - [x] B2C Checkout happy path
      - [x] B2B Checkout happy path
- - [x] Chrome @Parthlakhani (iPad Air)
      - [x] Blue Theme
      - [x] B2C Checkout happy path
      - [x] B2B Checkout happy path      
- [x] Android (Tablet - Samsung) 
- - [x] Chrome 
      - [x] Blue Theme
      - [x] B2C Checkout happy path
      - [x] B2B Checkout happy path
- - [x] Firefox 
      - [x] Blue Theme
      - [x] B2C Checkout happy path
      - [x] B2B Checkout happy path
- [x] Android (mobile) 
- - [x] Chrome @Pucek9 
      - [x] Blue Theme
      - [x] B2C Checkout happy path
      - [x] B2B Checkout happy path
- - [x] Firefox @Pucek9 
      - [x] Blue Theme
      - [x] B2C Checkout happy path
      - [x] B2B Checkout happy path

---
### 15. Functional Interoperability with non-Core Modules 
Owner: @hackergil  

- [ ] CPQ
- [ ] Smartedit
- [ ] CDS
- [x] CDC
- [x] Qualtrics

---
### 16. Performance Testing (Documentation Purposes Only)

- [ ] Homepage load 3.0 vs 4.0. 
- [ ] Checkout flow 3.0 vs 4.0
- [ ] Login/Logout flow 3.0 vs 4.0
- [ ] Lighthouse reports.  @giancorderoortiz 
- [ ] Others TBD
---
