### ISSUE TITLE
Test Plan 3.4.0

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#12690]
### Background

- Test plan lists the minimum necessary testing required for 3.4.0 release.
- Planned release date: Mid June 2021
- Regression testing to be handled mostly by automated testing.
- Manual testing required for new features only (where not covered by automation)
- ⚠️ ⚠️ ⚠️ Testing must be done only with 3.3.0 RCx
- This is a limited scope release
---
### New features for this release
- Minor modifications as described here: 
-- https://github.com/SAP/spartacus/issues/11955
-- https://github.com/SAP/spartacus/issues/12173

- Improvements to E2E tests as described below. 
---
### Server Links

- CCV2
-- https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/electronics-spa/en/USD/
-- https://b2bspastore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/powertools-spa/en/USD/

- Linux
-- http://spartacus-fdev9.eastus.cloudapp.azure.com:4200/powertools-spa/en/USD/

---
### Schematics

Confirm Spartacus 3.4 can be deployed in Windows, Mac, Linux using schematics script. 
https://github.com/SAP/spartacus/tree/develop/scripts/install

- [ ] Windows
- [x] Linux @giancorderoortiz 
- [x] Mac (be aware of machine crashes)

---
### Critical Open Bugs / QA Concerns

Improvements to E2E Tests. Eliminate flakyness of the following tests: 

- [x] B2B users test #11107
- [x] B2B users (and groups) e2e tests #11042
- [ ] Test b2b/regression/my-company/units.flaky-e2e-spec.ts #12267

New e2e Tests:
- [x] ~~E2E tests for Inventory Display~~ #11785 @ren-tham  ***postpone for 4.0***
- [x] ~~Export from cart e2e tests~~ #11764 @Matejk00 ***postpone for 4.0***
- [x] ~~a11y e2e tests for quick order~~ #11820 @dydome  ***postpone for 4.0***
- [x] ~~E2E tests for Quick Order~~ #11819 @dydome  ***postpone for 4.0***
- [x] ~~Cart validation e2e tests~~ #11909 @psmul  ***postpone for 4.0***
- [x] ~~Reorder E2E tests~~ #11963 @mszczepaniak ***postpone for 4.0***
---
### SSR Testing
- [x] Manually only. No availability of SSR e2e tests. 
- [x] Happy path in CCV2 

### Cypress Automated Regression Testing

- [x] Run full regression suite with 3.4.0 branch in CI.
-- Attach screenshot and link to the dashboard with final test results

- [ ]  Run all flaky tests either locally, CCV2, or Linux server. @giancorderoortiz 
-- In the case of actual failures, please investigate and open bugs if functional regression observed.
-- Manual execution of flaky tests here https://github.com/SAP/spartacus/issues/12692
---
### New Features Manual Testing
- [x] Bypass for this release only given the limited scope

---
### New Features Security Validation

- [ ] Whitesource. @hackergil 
- [x] Checkmarx. @giancorderoortiz 
- [x] Dynamic Scanning. @giancorderoortiz 

---
### New Features Accessibility Testing

- [ ] @developpeurweb please check there are no accessibility regressions in 3.4

---
### New Features Mobile/Exploratory-Smoke Testing

- [x] Bypass for this release only given the limited scope

---
### Functional Interoperability
Spartacus core team is still working on a strategy to tackle functional interoperability of modules. 
This section is left as a reference. 

- [ ] SmartEdit
- [ ] CDS
- [ ] CDC
- [ ] CPQ
- [ ] Qualtrics

**Comment by giancorderoortiz** [comment]
3.4.0 branch e2e test run: 

https://dashboard.cypress.io/projects/k3nmep/runs/15998/overview
https://dashboard.cypress.io/projects/k3nmep/runs/15837/overview

![Screen Shot 2021-06-07 at 6 47 18 AM](https://user-images.githubusercontent.com/46171897/121004338-8fe4fe80-c75c-11eb-8cc4-39192b682d60.png)
![Screen Shot 2021-06-07 at 6 49 19 AM](https://user-images.githubusercontent.com/46171897/121004339-907d9500-c75c-11eb-8151-d30b4fa498ca.png)
