### ISSUE TITLE
[Epic] Introduce the Cart Library

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#13044]
Move the cart and order related code to one or 2 feature libs

**Comment by KateChuen** [comment]
**Will test the following installations:**
- [x] installation script (where all the testing will be performed)
- [x] developer yarn way (only happy path) -> Because of issue https://github.com/SAP/spartacus/issues/15340, did most of B2B testing using yarn.


**Features that can be tested now:**
_**B2C**_
- [x] Coupons
- [x] Creating cart
- [x] Updating cart
- [x] Updating in cart modal
- [x] Cart merge
- [x] Saved Cart
- [x] Cart import/export
- [x] Placing orders
- [x] Wishlist

**Features to be tested after refactoring:**
**_B2B_**

- [x] Checkout
- [x] Replenishment order
- [x] Quick order
- [x] Saved cart
- [x] Order approval
- [x] Order History

**_B2C_**

- [x] Checkout
- [x] Guest Checkout
- [x] Express Checkout
- [x] Order History
- [x] Quick Order
- [x] Order Cancellation
- [x] Order Returns
- [x] ASM

**Issues found:**
https://github.com/SAP/spartacus/issues/14952
https://github.com/SAP/spartacus/issues/14955
https://github.com/SAP/spartacus/issues/14956
https://github.com/SAP/spartacus/issues/14957
https://github.com/SAP/spartacus/issues/14978
https://github.com/SAP/spartacus/issues/14979
https://github.com/SAP/spartacus/issues/14984
https://github.com/SAP/spartacus/issues/14986
https://github.com/SAP/spartacus/issues/15287
https://github.com/SAP/spartacus/issues/15295
https://github.com/SAP/spartacus/issues/15296
https://github.com/SAP/spartacus/issues/15298
https://github.com/SAP/spartacus/issues/15323
https://github.com/SAP/spartacus/issues/15324
https://github.com/SAP/spartacus/issues/15327
https://github.com/SAP/spartacus/issues/15329
https://github.com/SAP/spartacus/issues/15330
https://github.com/SAP/spartacus/issues/15339
https://github.com/SAP/spartacus/issues/15340
