### ISSUE TITLE
[MASTER] Pickup in Store (bopis)

### ISSUE THREAD

**Issue by saad-mo** [SAP/spartacus#13352]
# Overview

https://wiki.wdf.sap.corp/wiki/display/spar/Pickup+in+Store+Source+of+Truth

## Branch Name 
`epic/pickup-in-store` 

## Dedicated Dev Server 
`dev8` https://spartacus-fdev8.eastus.cloudapp.azure.com:9002

### POC Phase: 
- [x] #12098 
- [x] #4407

## TODOs:

1. Feature Lib: 
- [x] #13358
- [x] #4408

2. Product Details Page: 
- [x] #13473
- [x] #13474
- [x] #13531

3. Cart Page: 
- [x] #13532 
- [x] #13529
- [x] #13530
- [ ]  #13533
- [ ]  #13534

3. Checkout Pages: 
- [x] #13535
- [ ] Update Review Page to show in-store pickup products, store info 

4. Order Confirmation page
- [ ] Update Order Confirmation Page to show in-store pickup products, store info 

5. Order History Pages: 
- [ ] Update Order History Page Update  to show in-store pickup products, store info 

Overall Feature:
- [ ] Epic has been tested on a production-like server using Spartacus installation script
- [ ] Epic has been tested in all supported browsers and devices (Checklist on DoD page)
- [ ] Epic has sufficient end to end (cypress) test coverage
- [ ] Schematics code deprecations have been provided and tested
- [ ] Epic complies with [Security best practices](https://sap.github.io/spartacus-docs/security-best-practices/)
- [ ] Epic complies with [Accessibility best practices](https://sap.github.io/spartacus-docs/a11y-best-practices/)
- [ ] Epic CSS supports directionality (if required)
- [ ] Epic code scans have been conducted (sonar, whitesource, checkmarx)
- [ ] Epic renders successfully in SSR

## Audits/reviews

- [ ] Architecture review of the epic
- [ ] Security and threat modeling audit/review from the Security team
- [ ] Accessibility audit/review from the UX team

## New Library

If your epic will be introduced or introduces a new library:

- [ ] Library provides schematics to install the library
- [ ] Library modules can be lazy-loaded appropriately
- [ ] Library has been tested for a customer using Spartacus installation script

## Sample data

If the new feature requires new or updated sample data for a specific Commerce backend version:

- [ ] Sample data has been added to the sample data repo and merged to the next version to be released
- [ ] New sample data has been loaded and tested on a dev server
- [ ] New sample data has been loaded and tested in our CI server

## Documentation

- [ ] Documentation input is provided for it to be published on the doc site.

**Comment by saad-mo** [comment]
Issue moved to Jira
