### ISSUE TITLE
Epic Release: SAP EPD Visualization integration

### ISSUE THREAD

**Issue by sam-garland** [SAP/spartacus#13933]
Add an integration library that will allow for visual picking of spare parts from a 2D or 3D model.

This will include:
- A Spartacus component that acts as a wrapper around a UI5 `sap.ui.vk.Viewport` that will load 2D/3D data from the SAP EPD Visualization services
- A spare part list component
- A component that provides a responsive layout for the spare part list and viewer
- Services for mapping between commerce cloud product codes and visualizations/scene nodes in SAP EPD Visualization data

## Checklist

The following is a checklist for new epics or features acceptance for Spartacus, based on [our Definition of Done document](https://sap.github.io/spartacus-docs/definition-of-done/)

## General

- [x] Epic has been tested on a production-like server using Spartacus installation script
- [ ] Epic has been tested in all supported browsers and devices (Check list on DoD page)
- [x] Epic has sufficient end to end (cypress) test coverage
- [x] Schematics code deprecations have been provided and tested
- [ ] Epic complies with [Security best practices](https://sap.github.io/spartacus-docs/security-best-practices/)
- [ ] Epic complies with [Accessibility best practices](https://sap.github.io/spartacus-docs/a11y-best-practices/)
- [ ] Epic CSS supports directionality (if required)
- [ ] Epic code scans have been conducted (sonar, whitesource, checkmarx)
- [ ] Epic renders successfully in SSR

## Audits/reviews

- [ ] Architecture review of the epic (with @tobi-or-not-tobi)
- [ ] Security and threat modeling audit/review from the Security team
- [ ] Accessibility audit/review from the UX team

## New Library

If your epic will be introduced or introduces a new library:

- [ ] Library provides schematics to install the library
- [ ] Library modules can be lazy loaded appropriately
- [ ] Library has been tested for a customer using Spartacus installation script

## Sample data

If the new feature requires new or updated sample data for a specific Commerce backend version:

- [ ] Sample data has been added to the sampledata repo and merged to the next version to be released
- [ ] New sample data has been loaded and tested on a dev server
- [ ] New sample data has been loaded and tested in our CI server

## Documentation

- [ ] Documentation input is provided for it to be published on the doc site.
