### ISSUE TITLE
[still needed?] Create new e2e test to check extensible checkout improvements

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#2478]
Create new e2e tests for extensible checkout.
- [ ] Test if guards correctly protect routes.
- [ ] Check if url is correctly set on each step
- [ ] any other important test you might think of
