### ISSUE TITLE
Budget Managment [Master]

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#4649]
* Core functionality 
- [x] Create Budget OCC connections #4780
- [x] Core ngrx functionality #4747
- [x] Core unit tests #4781 

* StorefrontLib / assets
- [x] Create Budget pages #4783
- [x] Storefront unit tests #4784

* E2e
- [ ] QA #4786
- [ ] Prepare Budget Managment e2e tests #4785 

Preview: https://wiki.hybris.com/display/modelt/Budget+Management
