### ISSUE TITLE
Order Permission [Master]

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#4650]
* Core functionality 
- [x] Create OCC connections #6114
- [x] Core ngrx functionality #6116
- [x] Core unit tests #6115

- [x] Create Permission types OCC connections #6391
- [x] Core  Permission types ngrx functionality #6392
- [x]  Permission types core unit tests #6393 

----------------
HOLD:
* StorefrontLib / assets
- [x] Create pages #6199 
- [x] Storefront unit tests

* E2e
- [ ] QA
- [ ] Prepare e2e tests
