### ISSUE TITLE
[master] Anonymous consents improvements

### ISSUE THREAD

**Issue by znikola** [SAP/spartacus#5077]
MUST before 1.3.0:
- [x] - #5067 convert feature level toggle to the named feature
- [x] - #4495 Docs
- [x] - #5104 Revert to checkboxes + link styling
- [x] - #5078 Create a dialog trigger CMS component
- [x] - #5079 Make footer link CMS driven
- [x] - #5082 Create a common form component for both anonymous and registered consents
- [x] - #5006 Bug - consents are not transferred to other newly registered users
- [x] - #5080 TM - minimize localStorage data
- [x] - #5118 Share bannerVisible to all tabs 

Can be done AFTER before 1.3.0:
- [x] - #5081 Improve e2e tests
- [ ] - #4451 Conditionally store user and kyma tokens
- [x] - #4989 Deprecation instructions
