### ISSUE TITLE
Cart refactor for 2.0

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#5234]
### Improvements to do in the cart for 2.0 release
- [x] drop `cart-data.service` - #6806 
- [x] drop `cart.service` - #6832 
- [x] switch each usage of `cart.service` to `active-cart.service`
- [x] remove cart effects from the public API #4507 
- [x] completely drop `cart` part of the state
- [x] rename `getLoaded` to `isStable` (it is a bit misleading right know, because it for anonymous user it will return true even when we don't have a cart)
- [x] rename `multi-cart` to `carts`
- [x] drop actions used in `cart` branch of the store
- [x] adjust new actions (mostly adjust old effect for new actions only)
- [x] better payload in cart actions (especially in fail/success)

**Comment by marlass** [comment]
Futuristic ideas moved to #7245

**Comment by Zeyber** [comment]
QA:
- [x] drop cart-data.service
`cart-data.service` not found on develop branch
- [x] drop cart.service
`cart.service` not found on develop branch
- [x] switch each usage of cart.service to active-cart.service
`cart.service` not found on develop branch
- [x] remove cart effects from the public API
No more `effects` import in cart modules
- [x] completely drop cart part of the state
`cart` in store consists of `carts` entities now with other states such as `active` and `wishlist` pointing to the stores.
- [x] rename getLoaded to isStable (it is a bit misleading right know, because it for anonymous user it will return true even when we don't have a cart)
No more `getLoaded` in cart-related
- [x] rename multi-cart to carts
Renamed
- [x] drop actions used in cart branch of the store
- [x] adjust new actions (mostly adjust old effect for new actions only)
- [x] better payload in cart actions (especially in fail/success)
Cart activity in the redux tool all seems logical and readable.

`cart` and `wishlist` e2e tests pass locally.
