### ISSUE TITLE
CDS support master ticket

### ISSUE THREAD

**Issue by znikola** [SAP/spartacus#5338]
This ticket serves as a master ticket for CDS effort that includes merchandising carousel and profile tag.

# Next code review for merch carousel

- [x] - check the `cds.module.ts` and the adapter provider
- [x] - move the constructor after properties - https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/epic/cds-integration/projects/cds/src/cms-components/merchandising/carousel/merchandising-carousel/merchandising-carousel.component.ts#L20
- [x] - create a component service for the component and move the complex stream logic there, so that the component itself is very small and clean. An alternative is to move logic to the facade

# Next code review for profile tag

- [x] - `projects/cds/src/profiletag/profile-tag.injector.ts` - does it need service in the name?
- [x] - `projects/cds/src/profiletag/profile-tag.injector.ts` - `fromEventPattern`, does it really need an empty function as the `removeHandler`?
- [x] - `projects/cds/src/profiletag/profile-tag.injector.ts` - `initWindow` - specify `void` as the return type.

# Files to review before the final merge

- [x] `app.module.ts` - check for anything specific to CDS, such as `CdsModule` being imported. If we decide to keep it, then it should be `CdsModule.forRoot()`.
- [x] `projects/storefrontapp/src/environments/environment.ts` and `projects/storefrontapp/src/environments/environment.prod.ts`
- [x] `default-cds-config.ts` - double check all the values there. Everything specific to internal servers / configs / urls / keys should be left out.
- [x] `projects/storefrontapp/src/index.html`
- [x] `cypress.json` file should point back to dev17
- [x] check the README file - does it contain all the necessary steps on how to enable / use / configure CDS? If so, they can then just move it to the docs repo.
- [x] Check is the `CdsModule.forRoot()` import mentioned in the docs.
- [x] Are all CMS components listed in the README and integrated in spartacussampleaddon?
- [x] Update `PERSONALIZATION` to `PROFILE`. Make sure to mention in CDS docs that `PROFILE` consent has to be named exactly like that and exposed in order for CDS to work
- [x] check all the imports - if importing from `core` or `storefrontlib`, none should be relative. Search for these: `../core` and `../storefront`
- [x] in case ngrx is used, it should be added to `projects/cds/ng-package.json`
- [x] version in `projects/cds/package.json`?
- [x] on case dependency to `@spartacus/storefront` is needed, it should be defined in `projects/cds/ng-package.json`. 
- [x] check how the file structure looks in general.
- [x] double check what's exported in `public_api.ts`. Make sure that `projects/cds/src/services/cds-endpoints.service.ts` is not exported.
- [x] Revert `ci-scripts/build-for-deploy.sh` or talk to Gil about keeping it as is
- [x] Setup the API bot? `scripts/api-extractor-for-branch.sh`
- [x] Setup the release and release notes? Add `@spartacus/cds` to `scripts/templates/changelog.ejs`. Add two files e.g. `projects/storefrontlib/.release-it.changelog.json` and `projects/storefrontlib/.release-it.json` to `projects/cds`. This is a good example - https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/5496/files
- [x] compodoc configuration - `tsconfig.compodoc.json`
- [x] instead of `useClass` use `useExisting` - https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/5129
- [x] check the required configuration option in the `cds-config` file
- [x] check the build - https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/5360#discussion_r346710629
- [x] follow up on the fact that once the consent is granted for the first, the tracking can continue even in the case user withdraws it - `consentChanged` in the injector.ts has `take(1)`
- [x] copy-pasted `compare-equals-object` - projects/cds/src/utils/compare-equals-objects.ts
- [x] CORS - https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/5508/files#r349703281 Update the CCV2 configs
- [x] Currency missing from the merch carousel
- [x] Proper backend encoding - it's `EOS 500D &#43; 18-55mm IS &#43; EF-S 55-250 IS`, while it should be `EOS 500D + 18-55mm IS + EF-S 55-250 IS`
- [x] Convert the cds README.md to a proper doc file.
- [x] new shell app needs occBaseUrl needs to match with the main shell app's environment.ts
- [x] color stream sometimes produces undefined and sometimes empty object values. Check with `instanceof`.

# Future work

- [x] CI changes - once dev17 is stable:
  - [x] change the CI command back to `e2e:cy:cds:start-run-all-ci`
  - [x] enable the merch e2e test
- [ ] Create a generic Endpoint Service and extend / compose it in both CDS and OCC endpoint services (POST 2.0)
- [ ] Switch to using events service https://github.com/SAP/spartacus/issues/7161 (`should`)
- [ ] Minimize payload coming from CDS endpoint. Right now, the whole product is coming over the wire, while we'd like to get only the product ID with potentially some meta data (POST 2.0)

below are `COULD`
- [ ] Write API comments to the facades before exposing them 
- [ ] https://sap-cx.slack.com/archives/GPV2YLXC2/p1575988813047000?thread_ts=1575902507.021300&cid=GPV2YLXC2 - the special _all brands_ link `http://localhost:4200/electronics-spa/en/USD/Brands/all/c/brands` is configured in the bakcoffice, and as it’s CMS driven there’s no way to know the route upfront. We might want to have a config for this, and if customers change this route in the backoffice, they should also change the Spartacus config.
Not sure if this is something that should live in CDS lib though.
- [ ] Double check the dirty workaround for `DynamicTemplate` in `projects/cds/src/services/cds-endpoints.service.ts`
- [ ] when there are no primary images, display the default not-found image in `projects/cds/src/merchandising/cms-components/merchandising-carousel/merchandising-carousel.component.html`
