### ISSUE TITLE
Cost center [Master]

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#6110]
* Core functionality 
- [x] Create OCC connections #6364
- [x] Core ngrx functionality #6365
- [x] Core unit tests #6366
----------------
HOLD:
* StorefrontLib / assets
- [x] Create pages #6455 
- [x] Storefront unit tests

* E2e
- [ ] QA
- [ ] Prepare e2e tests

**Comment by Pucek9** [comment]
https://github.com/SAP/spartacus/labels/my-company%2Fcost-centers
