### ISSUE TITLE
Accessibility fixes - combined ticket

### ISSUE THREAD

**Issue by kacperknapik** [SAP/spartacus#6227]
Current a11y tests shows couple of problems with current codebase:

## Components:

- [x] https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/6309 quantity component (with '-' and '+' buttons, eg. on product page) is focused entirely, then each button/input is focused separately - we should focus only buttons/input

- [x] https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/6310 header navigation needs refactoring (was a bunch of people)

- [x] searchbox not tested - tested in #5858 (was Tobias)

## Routes/new features:

- [x] https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/6281 `/store-finder` not tested (was Mateusz)

- [x] #6311 `/my-account/notification-preference` not tested (was KungFu)

- [x] #6312 `/my-account/my-interests` not tested (was KungFu)

- [x] #6313 `/my-account/coupons` not tested (was KungFu)

- [x] #6314 `/?asm=true` not tested (should it be tested?) (was Patrick)
