### ISSUE TITLE
[MASTER] Engineering CCv2/CX recipe

### ISSUE THREAD

**Issue by zebercut** [SAP/spartacus#6321]
- [ ] [KR](https://github.com/SAP/cloud-commerce-spartacus-storefront/labels/1.5-e2e) Fix E2E of Spartacus running against OMS recipe (dev12) (Teams) (closed 23/27) (Progress 90%)

- [ ] [KR](https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/5448)  CCv2 with cx latest 1905 patch with CEP - as commit reference w/Travis (Gil) (1/2) (Progress 90%)

- [x] [KR](https://github.com/SAP/cloud-commerce-spartacus-storefront/labels/e2e-2005) E2E testing against 2005 (can be internal server for now) (Gil) (closed: 0/3)

- [x] [KR](https://github.com/SAP/cloud-commerce-spartacus-storefront/labels/repository-renaming) Rename repo's (Gil) (closed: 0/3)

- [ ] [KR](https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/6357) CCv2 has SSR (closed 0/1)

- [x] [KR](https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/5921) Spartacus on Azure (Marcin) (Jan) (0/1)

**Comment by Xymmer** [comment]
old master, closing
