### ISSUE TITLE
List all Calydon instances to be "set-as-base"

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#6404]
Create a **checklist** of the components and layouts having `calydon` instances to be transferred to the base theme:

**Comment by morganm58** [comment]
**Components:**
Cart
- [x] Cart-details
- [x] Cart-item-list
- [x] Cart-item
- [x] Cart-totals
- [x] Item-counter

Content
- [x] Navigation
- [x] Tab-paragraph-container

My Account
- [x] Consignment-tracking
- [x] Order-history
- [x] Order-return-request-list
- [x] Update-password

Product Carousel
- [x] product-carousel

Details
- [x] product-images

List
- [x] product-grid-item
- [x] product-list-item
- [x] product-list

Search
- [x] Search box

Product View
- [x] Product View

**Layouts**
- [x] Header

Page-templates
- [x] category-page
- [x] landing-page-2
- [x] Product-detail
- [x] Page-fold

**cx-base**

- [x] buttons
- [x] forms

**Comment by developpeurweb** [comment]
**For QA:**  
Please review the list above detailing the affected areas, mostly in the look out for visual bugs.

Despite the calydon code transfer, you may or not come across issues that may or not be old, please report them anyway even if it creates duplicates, I'll filter those out going forward. 

Please create one ticket per issue please.

**Comment by developpeurweb** [comment]
Calydon Migration Guide GH-7100

**Comment by KateChuen** [comment]
Tested on dev10, on chrome, firefox & safari.

**Components:**
Cart 
- [x] Cart-details -> Added a comment to an existing ticket: https://github.com/SAP/spartacus/issues/4517
- [x] Cart-item-list
- [x] Cart-item
- [x] Cart-totals
- [x] Item-counter
Created a ticket: https://github.com/SAP/spartacus/issues/7128

Content
- [x] Navigation
- [x] Tab-paragraph-container

My Account -> https://github.com/SAP/spartacus/issues/7131
- [x] Consignment-tracking (tested with dev17 backend)
- [x] Order-history -> https://github.com/SAP/spartacus/issues/7132, https://github.com/SAP/spartacus/issues/7133
- [ ] Order-return-request-list
- [x] Update-password

Product Carousel
- [x] product-carousel -> still an issue on safari as mentioned in https://github.com/SAP/spartacus/issues/6575

Details
- [x] product-images -> https://github.com/SAP/spartacus/issues/7129

List
- [x] product-grid-item -> https://github.com/SAP/spartacus/issues/7130
- [x] product-list-item
- [x] product-list

Search
- [x] Search box

Product View
- [x] Product View

**Layouts**
- [x] Header -> https://github.com/SAP/spartacus/issues/7131

Page-templates
- [x] category-page
- [x] landing-page-2
- [x] Product-detail
- [ ] Page-fold

**cx-base**
- [x] buttons: https://github.com/SAP/spartacus/issues/7151
- [x] forms


Other:	https://github.com/SAP/spartacus/issues/7152

**Comment by KateChuen** [comment]
Talked with Miguel and agreed to consider this ticket as done.
We don't know what page is a page-fold.
And couldn't get order returns, and Miguel said "it's mostly text alignments so not a major issue if misaligned"
