### ISSUE TITLE
[master] Schematics + Deprecation topics

### ISSUE THREAD

**Issue by znikola** [SAP/spartacus#6565]
(13/113)
- [x] [KR1](https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/6027) Mechanism for adding comments to the client's code is in place (1/1)
- [x] KR2 - Mechanism for migrating a deprecated constructor is in place (~#6432~ and ~#6520~) (2/2)
- [x] KR3 - Mechanism for migrating deprecated html/css changes is in place (~#6588~ and ~#6587~) (2/2)
- [ ] [KR4](https://github.com/SAP/cloud-commerce-spartacus-storefront/issues?utf8=%E2%9C%93&q=is%3Aopen+milestone%3A2.0+label%3Adeprecated-1.x+) all deprecation tickets are done (1/41) (Stan)
- [ ] [KR5](https://github.com/SAP/cloud-commerce-spartacus-storefront/issues?utf8=%E2%9C%93&q=is%3Aopen+milestone%3A2.0+label%3Abreaking-change+) all breaking change tickets are done (6/44) (mainly Obelix)
- [ ] [KR6](https://github.com/SAP/cloud-commerce-spartacus-storefront/issues?q=is%3Aopen+label%3Aupdate-schematics+milestone%3A2.0) all tickets that require a specific update schematic are done (1/15)
- [x] [KR7](https://github.com/SAP/cloud-commerce-spartacus-storefront/labels/code-deprecation) all deprecation TODOs from code (0/8)
- [x] [KR8](https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/6864) existing schematics work as before.

**Comment by znikola** [comment]
Closing as it's done.
