### ISSUE TITLE
[Main] Cart events and CartChangeEvent Implementation

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#6981]
Implement cart events:
- [x] add entry (do, success, fail) https://github.com/SAP/spartacus/issues/6989
- [x] remove entry (do, success, fail) https://github.com/SAP/spartacus/issues/7082
- [x] update entry (do, success, fail) https://github.com/SAP/spartacus/issues/7083
- [ ] add voucher (do, success, fail) https://github.com/SAP/spartacus/issues/7084
- [ ] remove voucher (do, success, fail) https://github.com/SAP/spartacus/issues/7085

And based on them implement:
- [ ] CartChangeEvent - aggregating the events for entry (add, remove, update) and voucher (add,remove) https://github.com/SAP/spartacus/issues/7086

**Comment by andreas-becker** [comment]
Hey @Platonn, you might want to add a cart event when the cart was merged.
This allows it to show a message to the customer after login (and the entries of the anonymout cart get merged).

**Comment by znikola** [comment]
Done so far:
- remove entry (success and fail)
- update entry (success and fail)
