### ISSUE TITLE
[MASTER] E2E tests remediation

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#7063]
Follow this ticket for updates regarding the e2e test in Spartacus repository.

## e2e tests status (Develop with CX 2005, Week of May 3, 2021)

Flaky test files: 18

## Current situation

- Developers have confidence in shipping new changes only if all tests (unit and e2e) pass and they cover all features and desired behaviors of libraries. Even one test that is always broken makes the rest of the tests less useful. You can't easily follow if your change broke something, you can't be confident and that makes you work slower
- "flaky" tests are tests that sometimes pass and sometimes don't pass. It can be because of problems with the test itself (waits, timeouts, other), Spartacus functionality, or backend problems. From a technical perspective, each one of those aspects can be improved to make the tests stable.
- Issues in this ticket are ordered with current priorities. Pick from the top.

## Current goals in order (prepare for all e2e in CI)
- [x] #11163 Run each test on different viewports (no dedicated mobile spec, but using viewport contexts)
- [x] #12265 Fix tests from `flaky` group. Once done, move them into the regression group. If you find a flaky test and it doesn't have a ticket, please create one and reference it here
- [ ] support testing against 2005, 2011, and CCv2 at the same time just by switching backend
	- [x] #7529 close-account (message based on locale)
	- [ ] Jobs to run against 2011, CCv2 (Migrate them out of Jenkins)
	- [x] #5433 smarter tests
	- [x] #7071 2005 issues
	- [x] #7985 Multi store e2e test strategy 
- [ ] sample data issues
	- [x] #7489 test-data manually imported
	- [ ] #7341 sample data improvements
	- [x] #6634 test data toggle
	- [x] #7489 Coupons not published (@hackergil)
- [ ] Propagate e2e fixes to the maintenance branch

## Future goals
- [x] prepare setup for CDS e2e tests
	- [x] #7462 script setup for CDS
- [ ] Check code coverage of e2e tests
- [x] #14027
	- [x] #4291 e2e for order cancellation
	- [x] #4290 e2e for return order
	- [ ] #5784 returns
	- [ ] #5691 returns
	- [ ] #5256 more coupons scenarios
	- [x] #5144 back button on infinite scrolling
	- [x] #5020 base site dynamic configuration
- [x] Test SSR with e2es
	- [x] #2745 Choose which tests to run for SSR
	- [x] #2979 verify SSR starts
- [x] simplify CI configuration (lot of scripts, configurations, commands)
	- [ ] #6361 don't depend on custom routing config in sample app
- [ ] Make tests more maintainable
	- [x] #2753 util function for search
	- [x] #4672 improve logging in tests
- [ ] make tests faster
- [ ] make them easier to write (better structure, utils, practices)

**Comment by giancorderoortiz** [comment]
With new azure infrastructure, it can now be possible to parallelize e2e test runs. 
Commits should run full e2e regression suite, not only smoke tests.  (not possible with old infra)
We have 3 machines as backend for a load balancer. 
I'll be adding 3 more, so you'll have 6 exact VMs (same backend CX version, same sample data + additional config) to run tests in parallel. 
Can reduce (in theory) regression test run from ~70 minutes to ~12 minutes. 

![Screen Shot 2020-09-20 at 10 33 57 AM](https://user-images.githubusercontent.com/46171897/93713901-f1146580-fb2c-11ea-8c21-26d2358024ea.png)

@hackergil , @Xymmer @zebercut

**Comment by hackergil** [comment]
Closing this one. I will create several tickets with the remaining tasks
