### ISSUE TITLE
Regression testing for 2.0 release

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#7126]
**Test against 1905**
Can use:
- https://dev-com-3.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/
-https://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/ 

- [x] **Run all the E2E tests** on the nightly branch on jenkins (Marcin) - covered in https://github.com/SAP/spartacus/issues/7799
Note: Make sure that ALL the tests are being run (about 90 tests, including the flaky tests). 
OR run them from your computer, pointing to dev17 server.

**Manually test the features that are failing:**
- [x] to come from release masters - Marcin - covered in https://github.com/SAP/spartacus/issues/7799

**Do a smoke test of these features manually**, since there's no E2E tests for them yet or they are flaky:
~~Cancel/Return~~ - Jimmy (Imported impex, but cancel/returns not enabled on 1905)
- [x] Smartedit (Wei lead, but get someone else to do it) - Kate
- [x] Qualtrics - Brian
- [x] Coupons - GC
- [x] Broken tabbing order (related to e2e accessibility? kacper fixing?) - Kate
- [x] Accessibility (checkout with keyboard nav on all 3 browsers) - Kate
- [x] Checkout as a persistent user

**Do a smoke test (happy path) on these browsers:**
- [x] safari - Kate: https://github.com/SAP/spartacus/issues/7817
- [x] firefox - Kate
- [ ] Edge Windows - Farzin
- ... more! mobile phones, tablet, etc.  (GC -> Ipad Pro)

**Test against 2005**
- http://dev-com-2.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/
- https://dev-com-8.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

- [x] Run the e2e tests pointing to dev7 server as backend (there's already a jenkins job for it) - Brian
- [x] Retest manually failing tests (make list of differences of failures between 1905 and 2005) - Brian

Redo manual set (cancel/return etc.) against 2005 as well 
- [x] Cancel/Return - Jimmy
- [x] Smartedit (Wei lead, but get someone else to do it) - Kate
- [x] Qualtrics - Brian
- [x] Coupons (GC)
- [x] Broken tabbing order (related to e2e accessibility? kacper fixing?)  - Kate
- [x] Accessibility (checkout with keyboard nav on all 3 browsers) - Kate
- [x] Checkout as a persistent user - Kate

Don't do for 2005: smoketest browsers

The 2005 goal is to see if we see any differences at all... in the future

**Manually test the features that are failing against 2005 backend:**

- [x] regression/cart.e2e-spec.ts #7841 - Kate: couldn't test apparel. and couldn't test out of stock product because backoffice isn't working for 2005. Can't go to products in backoffice, we get an error "cannot execute search". 
- [x] smoke/checkout-flow.e2e-spec.ts #7842 - Kate
- [x] smoke/currency.e2e-spec.ts #7846 - Kate
- [x] smoke/language.e2e-spec.ts #7848 - Kate
- [x] smoke/product-search.e2e-spec.ts #7849 - Kate

**Comment by giancorderoortiz** [comment]
@Xymmer  Several e2e tests against 2005 backend fail. I'll open tickets individually.
