### ISSUE TITLE
Epic: directionality

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#837]
We're already doing a pretty good job at directionality. Directionality is driven by CSS only, mainly by using modern layout options such as flexbox. There are a few areas that we need to finalize
- Consistently use CSS logical properties, drop physical, direction and dimension mapping (i.e. use `margin-inline-start` over `margin-right`). Logical properties are well supported in [ever green browsers](https://caniuse.com/#search=logical%20properties)
- Drop or override the bootstrap `text-align` in the reboot mixin.

Additionally, we need to 
- collect a list of things that can't be done with CSS (star rating component is one of them)
- evaluate (if possible to) auto apply directionality based on the browser or site language setup

Steps: 
- [x] Language driven direction detection (#8372)
- [x] Icon flipping of (some) icons (#8392)
- [x] make fixes in CSS layer to move from rtl to logical properties ( this is taken care of in #8379 )
- [ ] Fix additional issues  
    - ~~star rating (fix as part of #8392)~~
    - ~~layout of the banners on the home page (these are ordinary logical properties)~~
    - the horizontal page loader is ltr orientated. 
      https://engineering.atspotify.com/2019/04/15/right-to-left-the-mirror-world/ tells that music loaders should not be mirrored

An interesting read from Spotify on directionality: https://engineering.atspotify.com/2019/04/15/right-to-left-the-mirror-world/

**Comment by Xymmer** [comment]
Most directionality is provided out of the box, we might need to investigate what we can do further. but not for 1.0.
