### ISSUE TITLE
My Company UX improvements

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#8537]
The new My Company UX requires some improvements. While being under pressure of the release, we've made a prioritised list based on effort and importance. 

- [x] Split View improvements (required for 2.1) #8535 
- [x] Split View adaption in my company #8208
- [ ] Introduce breadcrumb for child routes (#8490)
- [x] Action buttons/links instead of icon buttons (keep lowercase)
- [x] Optimised list layout
- [x] Sorting drop down
- [x] Misc UI changes
- [ ] Tree view component merged in list component (#8199)
- [x] Landing Page
- [ ] Organization Navigation in my account (postponed after 3.0)

Stretch:
- [x] Dialog confirmation changes (stretch because we hvae dialogs now)

**Comment by tobi-or-not-tobi** [comment]
Most of this is introduced with #8924. The tree and breadcrumb are done in isolation.
