### ISSUE TITLE
Visuals Refresh around 3.0 [master]

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#8552]
- [ ] New theme (Mikel) (#8511)

Electronics
- [x] Add new products to sample data that are part of new categories (tvs: #9266; phones: #9266) (Wei/Patrick)
- [x] Update home page carousels to point to new products (#9541, Saad)
- [ ] Update banners with new images with dynamic text (text not in image file) (#9517, Saad)
- [x] Update category links - point to new categories of products (Wei/Patrick)

Next:

Powertools
- [x] Add new products to sample data that are part of new categories
- [x] Update home page carousels to point to new products
- [x] Update banners with new images that have static text
- [x] Update category links - point to new categories of products

Apparel:
- [ ] Add new products to sample data that are part of new categories
- [ ] Update home page carousels to point to new products
- [ ] Update banners with new images that have static text
- [ ] Update category links - point to new categories of products

**Comment by giancorderoortiz** [comment]
Will regression/smoke e2e tests be impacted by this visual refresh? 
Are there new e2e tests being written that use these new products/categories/banners?
