### ISSUE TITLE
Follow-up on ng10 update

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#8930]
During the update several issues has arose:
- [x] angular cli 10 has dropped some function Spartacus used in schematics. They has been moved to our code base but more unit test are needed #8964 
~- also since schematics are not published yet changing ts configuration was needed - let's revert that once published~
- [x] deprecations:
   - [x] remove entry components as they're not needed anymore in ng10 #8965
   - [x] replace `TestBed.get` with `TestBed.inject` #9064
   - [x] replace `async` with `waitForAsync` #9065
   - [x] Fix NgPackagrBuilderOptions import #9068

Also following tasks should be performed:
- [x] check migrations and schematics work fine with the new setup and fix if needed (or create tickets), related to #9104 
- [x] check documentation needs to be updated and update if needed (or create tickets)

related to #8814
