### ISSUE TITLE
Handle deprecations for route-driven breadcrumbs

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#9551]
According to #9075 several depractions needs to be handled, including:
- [x] changed translations
- [x] changed configs
- [x] changed constructors 

Wherever possible use schematics migrations.

**Comment by Platonn** [comment]
- [x] changed constructors:
   - [x] https://github.com/SAP/spartacus/pull/9075/files#diff-92c4dd9b7380e30d5ce2d508fc3f5d3ea5aa792da33b097cc62a898b0ebd797bR50 - Not breaking change. The service was introduced lately in 3.0-next
   - [x] https://github.com/SAP/spartacus/pull/9075/files#diff-cf1240e647a076bb723eea5154dd4f0be5914e82c3ab10af0f47ba9be9c49b89R55 - will be handled in https://github.com/SAP/spartacus/issues/9106
   - [x] https://github.com/SAP/spartacus/pull/9075/files#diff-3201998618d8872908929c09770fd2e5f2dda709bfa96edee6cd4bd7b402359dR23 - Not breaking change. The service was introduced lately in 3.0-next
- [x] Translations - not a braeking change. The translations were introduced lately in 3.0-next https://github.com/SAP/spartacus/pull/9075/files#diff-74e99ef711f0761f9f547e283588bc22150e485d0305e893128bafc66ac1effbR40
- [x] changed interface type https://github.com/SAP/spartacus/pull/9075/files#diff-43707980e31f9c6fe5d0be31c399a383092714445bacd74dbe1afeeff55b581aR58 - handled in https://github.com/SAP/spartacus/issues/9551
- [x] changed method's return type https://github.com/SAP/spartacus/pull/9075/files#diff-27f758d81b62423d1708fe22680312eaab7ed578550b037e617e0946924eb943R158 - handled in https://github.com/SAP/spartacus/issues/9551
