### ISSUE TITLE
Various migrations

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#9650]
- [x] according to https://github.com/SAP/spartacus/pull/8990 exported class name has been changed | @Platonn edit: not a breaking change. it was not in public API before the change
- [x] `projects/core/src/product/model/search-config.ts` - param name change in the interface, #8874, #9028  | @bgambocjaviniar edit: already being done in https://github.com/SAP/spartacus/pull/9623/files
- [x] `projects/core/src/store-finder/store/actions/find-stores.action.ts` - constructor changed, #8874
- [x] `projects/storefrontlib/src/shared/components/item-counter/item-counter.component.ts` - #7633, removed function, changed class
- [x] `projects/storefrontlib/src/cms-components/myaccount/update-email/update-email.component.ts` - changed public function to async #9546

**Comment by bgambocjaviniar** [comment]
PR: GH-9662
